from enum import Enum

class CabinNarrow(Enum):
	SIXABREAST = "SIXABREAST"
	FIVEABREAST = "FIVEABREAST"
	FOURABREAST = "FOURABREAST"
	THREEBREAST = "THREEBREAST"
	TWOABREAST = "TWOABREAST"
	

